language: objective-c
osx_image: xcode9.1

before_install:
  - pod repo update --silent
  - gem install xcpretty

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace GOT-Challenge-Swift.xcworkspace -scheme 'GOT-Challenge-SwiftTests' -destination "platform=iOS Simulator,OS=11.1,name=iPhone X" build test CODE_SIGN_IDENTITY=- | xcpretty -c
