language: objective-c
osx_image: xcode9

before_install:
  - pod repo update --silent
  - gem install xcpretty

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace GOT-Challenge-Swift.xcworkspace -scheme 'GOT-Challenge-Swift' -destination 'platform=iOS Simulator,name=iPhone 6s Plus,OS=11.0' build test CODE_SIGN_IDENTITY=- | xcpretty -c
